export default {
  GET_QUESTIONS_START: 'questions/GET_QUESTIONS_START',
  GET_QUESTIONS_SUCCESS: 'questions/GET_QUESTIONS_SUCCESS',
  GET_QUESTIONS_ERROR: 'questions/GET_QUESTIONS_ERROR',

  GET_QUESTIONS_MORE_START: 'questions/GET_QUESTIONS_MORE_START',
  GET_QUESTIONS_MORE_SUCCESS: 'questions/GET_QUESTIONS_MORE_SUCCESS',
  GET_QUESTIONS_MORE_ERROR: 'questions/GET_QUESTIONS_MORE_ERROR',
};
