export default {
  SIGN_UP_START: 'auth/SIGN_UP_START',
  SIGN_UP_SUCCESS: 'auth/SIGN_UP_SUCCESS',
  SIGN_UP_ERROR: 'auth/SIGN_UP_ERROR',

  SIGN_IN_START: 'auth/SIGN_IN_START',
  SIGN_IN_SUCCESS: 'auth/SIGN_IN_SUCCESS',
  SIGN_IN_ERROR: 'auth/SIGN_IN_ERROR',

  SIGN_OUT: 'auth/SIGN_OUT',
};
