export default {
  GET_ANSWERS_BY_QUESTION_ID_START: 'answers/GET_ANSWERS_BY_QUESTION_ID_START',
  GET_ANSWERS_BY_QUESTION_ID_SUCCESS: 'answers/GET_ANSWERS_BY_QUESTION_ID_SUCCESS',
  GET_ANSWERS_BY_QUESTION_ID_ERROR: 'answers/GET_ANSWERS_BY_QUESTION_ID_ERROR',

  GET_ANSWERS_BY_QUESTION_ID_MORE_START:
  'answers/GET_ANSWERS_BY_QUESTION_ID_MORE_START',
  GET_ANSWERS_BY_QUESTION_ID_MORE_SUCCESS:
  'answers/GET_ANSWERS_BY_QUESTION_ID_MORE_SUCCESS',
  GET_ANSWERS_BY_QUESTION_ID_MORE_ERROR:
  'answers/GET_ANSWERS_BY_QUESTION_ID_MORE_ERROR',
};
