export default {
  GET_ANSWERS_BY_QUESTION_ID_START: 'answers/GET_ANSWERS_BY_QUESTION_ID_START',
  GET_ANSWERS_BY_QUESTION_ID_SUCCESS: 'answers/GET_ANSWERS_BY_QUESTION_ID_SUCCESS',
  GET_ANSWERS_BY_QUESTION_ID_ERROR: 'answers/GET_ANSWERS_BY_QUESTION_ID_ERROR',

  GET_ANSWERS_BY_QUESTION_ID_MORE_START:
  'answers/GET_ANSWERS_BY_QUESTION_ID_MORE_START',
  GET_ANSWERS_BY_QUESTION_ID_MORE_SUCCESS:
  'answers/GET_ANSWERS_BY_QUESTION_ID_MORE_SUCCESS',
  GET_ANSWERS_BY_QUESTION_ID_MORE_ERROR:
  'answers/GET_ANSWERS_BY_QUESTION_ID_MORE_ERROR',

  SEND_ANSWER_TO_QUESTION_START: 'answers/SEND_ANSWER_TO_QUESTION_START',
  SEND_ANSWER_TO_QUESTION_SUCCESS: 'answers/SEND_ANSWER_TO_QUESTION_SUCCESS',
  SEND_ANSWER_TO_QUESTION_ERROR: 'answers/SEND_ANSWER_TO_QUESTION_ERROR',
};
